### ISSUE TITLE
empty files in lang_resources/giza

### ISSUE THREAD

**Issue by lupo01** [lspecia/quest#11]
Error during loading Giza - file lang_resources/giza/train.es_en.actual.ti.final is empty.

**Comment by lspecia** [comment]
We are not storing the resources on Github because of space constraints. You can find links to all resources used in the share task from: https://github.com/lspecia/QualityEstimation. Of course you can also provide the file for a new task.

**Comment by lefterav** [comment]
Anyway, I think then this folder or at least the empty files should be removed, since giving out empty files is missleading. lupo01 is working on the installation script, which possible includes removing lang_resources and re-locate them in another server.

**Comment by lspecia** [comment]
Ok - I agree, I see no reason for an empty file to be  there
