### ISSUE TITLE
Development Guide Missing

### ISSUE THREAD

**Issue by owo** [lspecia/quest#24]
## Problem:

In the _README_, under **Running**, you wrote "More information about these scripts and the code itself can be found on the development guide (dist/MTFeatures.pdf)."
However, _dist/MTFeatures.pdf_ does not exist.
## Solution:

Point to _doc/MTFeatures.docx_ instead or, preferably, compile _doc/MtFeatures.docx_ to _doc/MtFeatures.pdf_ and point to that.

**Comment by owo** [comment]
Hi,
I have also noticed that the development guide in this repo is incomplete compared to the one in stable release.
Is there a chance you can include it here?

Thanks.

**Comment by kashifshah** [comment]
Done. 

Thanks.
