### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by lefterav** [lspecia/quest#8]
Devise an one-step installation script that will download and settle resources tools as necessary
1. No heavy stuff should be downloaded from github 'cause of the account quota
2. Download resources and tools from the original websites or, if needed from our own ftp/http servers
3. For some tools that are not installable by a script (e.g SRILM), specify detailed documentation

**Comment by lefterav** [comment]
I don't know if this should be a different issue, but some questions have arisen:
(a) which is the own, non-github server where the compiled resources and binaries will reside
(b) we assume at first that the resources are all provided by ours. When this script is succesful, we can later devise a mechanism for creating them from external tools.

**Comment by lspecia** [comment]
I am preparing an ftp server for the resources - so it will be a Sheffield server.
Agree about helping users creating resources for other datasets

**Comment by lefterav** [comment]
The script has been finished. The new server's URL should be entered
